; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "s21-notify"
#define MyAppVersion "1.0.0.2-beta"
#define MyAppPublisher "Vladislav Panov"
#define MyAppURL "https://fr-space.ru"
#define MyAppExeName "s21-notify.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D13BEBFA-7425-44D3-85FE-AE72D6CA8B0C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=no
DefaultGroupName={#MyAppName}
;LicenseFile=d:\_apps\s21_notify\dist\COPYING.txt
LicenseFile=
; Uncomment the following line to run in non administrative install mode (install for current user only.)
OutputBaseFilename=s21-notify-{#MyAppVersion}
SetupIconFile=d:\_apps\s21_notify\dist\data\icon.ico
UninstallDisplayIcon=d:\_apps\s21_notify\dist\data\icon.ico
UninstallDisplayName={#MyAppName}
PrivilegesRequired=none
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardSmallImageFile=d:\_apps\s21_notify\dist\banner1.bmp
WizardImageFile=d:\_apps\s21_notify\dist\banner2.bmp
CloseApplications=force

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Files]
Source: "d:\_apps\s21_notify\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; \
    BeforeInstall: TaskKill('{#MyAppExeName}')
Source: "d:\_apps\s21_notify\dist\s21-updater.exe"; DestDir: "{app}"; Flags: ignoreversion; \
    BeforeInstall: TaskKill('s21-updater.exe')
Source: "d:\_apps\s21_notify\dist\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ISTask.dll; DestDir: "{app}"

[Code]
procedure TaskKill(FileName: String);
var
  ResultCode: Integer;
begin
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/f /im ' + '"' + FileName + '"', ExpandConstant('{sys}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

function InitializeSetup(): Boolean;
begin
  TaskKill('{#MyAppExeName}');
  TaskKill('s21-updater.exe');
  Result := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    TaskKill('{#MyAppExeName}');
    TaskKill('s21-updater.exe');
  end;
end;      

[Run]
Filename: "cmd"; Parameters: "/C icacls ""{app}\s21-notify.exe"" /grant %USERNAME%:(F)"; Flags: runhidden
Filename: "cmd"; Parameters: "/C icacls ""{app}\s21-updater.exe"" /grant %USERNAME%:(F)"; Flags: runhidden

; Установка полных прав для текущего пользователя на файл events.db
Filename: "cmd"; Parameters: "/C icacls ""{app}\data\events.db"" /grant %USERNAME%:(OI)(CI)F"; Flags: runhidden

; Установка полных прав для текущего пользователя на директорию data
Filename: "cmd"; Parameters: "/C icacls ""{app}\data"" /grant %USERNAME%:(OI)(CI)F"; Flags: runhidden

[Icons]
;Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{userstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
;Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{app}\unins000.exe"; IconFilename: "{app}\ui_images\uninstall.ico"; Tasks: startmenu

;[Run]
;Filename: "{app}\{#MyAppExeName}"; Flags: runasoriginaluser

;[Run]
;Filename: "{app}\{#MyAppExeName}"; Parameters: "/autostart"; Flags: runasoriginaluser

[UninstallDelete]
Type: filesandordirs; Name: "{app}";

;[Registry]
;Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "s21-notify"; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue
